#!/usr/bin/env ruby

require 'net/http'
require 'securerandom'

def uuid
  ary = SecureRandom.random_bytes(16).unpack("NnnnnN")
  ary[2] = (ary[2] & 0x0fff) | 0x4000
  ary[3] = (ary[3] & 0x3fff) | 0x8000
  "%08x-%04x-%04x-%04x-%04x%08x" % ary
end

user = IO.popen("whoami", "r+").gets.chomp
program = ARGV[0].to_s
dbconf = "/Users/#{user}/Library/Gyazo/dropbox"

if not File.exist?(dbconf) then
  system "mkdir -p #{File.dirname(dbconf)}"
  system "bash #{File.dirname(__FILE__)}/uploader"
  ret = $?.exitstatus
  exit 0 if $?.exitstatus == 1
end

# capture png file
name = uuid() + ".png"
tmpfile = "/tmp/#{name}"
imagefile = ARGV[1]

if imagefile && File.exist?(imagefile) then
  system "sips -s format png \"#{imagefile}\" --out \"#{tmpfile}\""
else
  system "screencapture -i \"#{tmpfile}\""
  if File.exist?(tmpfile) then
    system "sips -d profile --deleteColorManagementProperties \"#{tmpfile}\""  
  end
end

if !File.exist?(tmpfile) then
  exit
end

#imagedata = File.read(tmpfile)
system "bash #{File.dirname(__FILE__)}/uploader upload #{tmpfile} #{name}"
output=`bash #{File.dirname(__FILE__)}/uploader share #{name}`
url = /https[\S]+/.match(output)[0]
File.delete(tmpfile)
system "open #{url}"
